"""File generated by TLObjects' generator. All changes will be ERASED"""
from ...tl.tlobject import TLObject
from ...tl.tlobject import TLRequest
from typing import Optional, List, Union, TYPE_CHECKING
import os
import struct
from datetime import datetime
if TYPE_CHECKING:
    from ...tl.types import TypeInputMedia, TypeInputPeer, TypeInputReplyTo, TypeInputRichMessage, TypeInputUser, TypeMessageEntity, TypeReplyMarkup



class DeleteMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0xa3c0d511
    SUBCLASS_OF_ID = 0xf5b399ac

    def __init__(self, peer: 'TypeInputPeer', receiver_id: 'TypeInputUser', id: int):
        """
        :returns Bool: This type has no constructors.
        """
        self.peer = peer
        self.receiver_id = receiver_id
        self.id = id

        super().__init__()

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))
        self._check_peer(self.peer)
        self.receiver_id = utils.get_input_user(await client.get_input_entity(self.receiver_id))
        self._check_peer(self.receiver_id)

    def to_dict(self):
        return {
            '_': 'DeleteMessageRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'receiver_id': self.receiver_id.to_dict() if isinstance(self.receiver_id, TLObject) else self.receiver_id,
            'id': self.id
        }

    def _bytes(self):
        self._assert_no_forbidden_constructors()
        return b''.join((
            b'\x11\xd5\xc0\xa3',
            self.peer._bytes(),
            self.receiver_id._bytes(),
            struct.pack('<i', self.id),
        ))

    @classmethod
    def from_reader(cls, reader):
        _peer = reader.tgread_object()
        _receiver_id = reader.tgread_object()
        _id = reader.read_int()
        return cls(peer=_peer, receiver_id=_receiver_id, id=_id)


class GetCallbackAnswerRequest(TLRequest):
    CONSTRUCTOR_ID = 0x3fa464c8
    SUBCLASS_OF_ID = 0x6c4dd18c

    def __init__(self, peer: 'TypeInputPeer', id: int, data: Optional[bytes]=None):
        """
        :returns messages.BotCallbackAnswer: Instance of BotCallbackAnswer.
        """
        self.peer = peer
        self.id = id
        self.data = data

        super().__init__()

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))
        self._check_peer(self.peer)

    def to_dict(self):
        return {
            '_': 'GetCallbackAnswerRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'id': self.id,
            'data': self.data
        }

    def _bytes(self):
        self._assert_no_forbidden_constructors()
        return b''.join((
            b'\xc8d\xa4?',
            struct.pack('<I', (0 if self.data is None or self.data is False else 2)),
            self.peer._bytes(),
            struct.pack('<i', self.id),
            b'' if self.data is None or self.data is False else (self.serialize_bytes(self.data)),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _peer = reader.tgread_object()
        _id = reader.read_int()
        if flags & 2:
            _data = reader.tgread_bytes()
        else:
            _data = None
        return cls(peer=_peer, id=_id, data=_data)


class ReportMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0x8704f2bf
    SUBCLASS_OF_ID = 0xacd3f438

    def __init__(self, peer: 'TypeInputPeer', id: int, option: bytes, message: str):
        """
        :returns ReportResult: Instance of either ReportResultChooseOption, ReportResultAddComment, ReportResultReported.
        """
        self.peer = peer
        self.id = id
        self.option = option
        self.message = message

        super().__init__()

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))
        self._check_peer(self.peer)

    def to_dict(self):
        return {
            '_': 'ReportMessageRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'id': self.id,
            'option': self.option,
            'message': self.message
        }

    def _bytes(self):
        self._assert_no_forbidden_constructors()
        return b''.join((
            b'\xbf\xf2\x04\x87',
            self.peer._bytes(),
            struct.pack('<i', self.id),
            self.serialize_bytes(self.option),
            self.serialize_bytes(self.message),
        ))

    @classmethod
    def from_reader(cls, reader):
        _peer = reader.tgread_object()
        _id = reader.read_int()
        _option = reader.tgread_bytes()
        _message = reader.tgread_string()
        return cls(peer=_peer, id=_id, option=_option, message=_message)


class SendMessageRequest(TLRequest):
    CONSTRUCTOR_ID = 0x68cbd09f
    SUBCLASS_OF_ID = 0x8af52aac

    def __init__(self, peer: 'TypeInputPeer', receiver_id: 'TypeInputUser', message: str, query_id: Optional[int]=None, entities: Optional[List['TypeMessageEntity']]=None, media: Optional['TypeInputMedia']=None, reply_markup: Optional['TypeReplyMarkup']=None, rich_message: Optional['TypeInputRichMessage']=None, random_id: int=None, reply_to: Optional['TypeInputReplyTo']=None):
        """
        :returns Updates: Instance of either UpdatesTooLong, UpdateShortMessage, UpdateShortChatMessage, UpdateShort, UpdatesCombined, Updates, UpdateShortSentMessage.
        """
        self.peer = peer
        self.receiver_id = receiver_id
        self.message = message
        self.query_id = query_id
        self.entities = entities
        self.media = media
        self.reply_markup = reply_markup
        self.rich_message = rich_message
        self.random_id = random_id if random_id is not None else int.from_bytes(os.urandom(8), 'big', signed=True)
        self.reply_to = reply_to

        super().__init__()

    async def resolve(self, client, utils):
        self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))
        self._check_peer(self.peer)
        self.receiver_id = utils.get_input_user(await client.get_input_entity(self.receiver_id))
        self._check_peer(self.receiver_id)
        if self.media:
            self.media = utils.get_input_media(self.media)
            self._check_peer(self.media)

    def to_dict(self):
        return {
            '_': 'SendMessageRequest',
            'peer': self.peer.to_dict() if isinstance(self.peer, TLObject) else self.peer,
            'receiver_id': self.receiver_id.to_dict() if isinstance(self.receiver_id, TLObject) else self.receiver_id,
            'message': self.message,
            'query_id': self.query_id,
            'entities': [] if self.entities is None else [x.to_dict() if isinstance(x, TLObject) else x for x in self.entities],
            'media': self.media.to_dict() if isinstance(self.media, TLObject) else self.media,
            'reply_markup': self.reply_markup.to_dict() if isinstance(self.reply_markup, TLObject) else self.reply_markup,
            'rich_message': self.rich_message.to_dict() if isinstance(self.rich_message, TLObject) else self.rich_message,
            'random_id': self.random_id,
            'reply_to': self.reply_to.to_dict() if isinstance(self.reply_to, TLObject) else self.reply_to
        }

    def _bytes(self):
        self._assert_no_forbidden_constructors()
        return b''.join((
            b'\x9f\xd0\xcbh',
            struct.pack('<I', (0 if self.query_id is None or self.query_id is False else 1) | (0 if self.entities is None or self.entities is False else 2) | (0 if self.media is None or self.media is False else 4) | (0 if self.reply_markup is None or self.reply_markup is False else 8) | (0 if self.rich_message is None or self.rich_message is False else 16) | (0 if self.reply_to is None or self.reply_to is False else 32)),
            self.peer._bytes(),
            self.receiver_id._bytes(),
            b'' if self.query_id is None or self.query_id is False else (struct.pack('<q', self.query_id)),
            self.serialize_bytes(self.message),
            b'' if self.entities is None or self.entities is False else b''.join((b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.entities)),b''.join(x._bytes() for x in self.entities))),
            b'' if self.media is None or self.media is False else (self.media._bytes()),
            b'' if self.reply_markup is None or self.reply_markup is False else (self.reply_markup._bytes()),
            b'' if self.rich_message is None or self.rich_message is False else (self.rich_message._bytes()),
            struct.pack('<q', self.random_id),
            b'' if self.reply_to is None or self.reply_to is False else (self.reply_to._bytes()),
        ))

    @classmethod
    def from_reader(cls, reader):
        flags = reader.read_int()

        _peer = reader.tgread_object()
        _receiver_id = reader.tgread_object()
        if flags & 1:
            _query_id = reader.read_long()
        else:
            _query_id = None
        _message = reader.tgread_string()
        if flags & 2:
            reader.read_int()
            _entities = []
            for _ in range(reader.read_int()):
                _x = reader.tgread_object()
                _entities.append(_x)

        else:
            _entities = None
        if flags & 4:
            _media = reader.tgread_object()
        else:
            _media = None
        if flags & 8:
            _reply_markup = reader.tgread_object()
        else:
            _reply_markup = None
        if flags & 16:
            _rich_message = reader.tgread_object()
        else:
            _rich_message = None
        _random_id = reader.read_long()
        if flags & 32:
            _reply_to = reader.tgread_object()
        else:
            _reply_to = None
        return cls(peer=_peer, receiver_id=_receiver_id, message=_message, query_id=_query_id, entities=_entities, media=_media, reply_markup=_reply_markup, rich_message=_rich_message, random_id=_random_id, reply_to=_reply_to)

